Viettut\Entity\Core\Card:
    type: entity
    table: viettut_card
    repositoryClass: Viettut\Repository\Core\CardRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        hash:
            type: text
            nullable: false
        data:
            type: json_array
            nullable: false
        gallery:
            type: json_array
            nullable: true
        weddingDate:
            type: datetime
            nullable: false
        video:
            type: string
            nullable: true
        videoId:
            type: string
            nullable: true
        validVideo:
            type: boolean
            options:
                default: false
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        latitude:
            type: text
            nullable: true
        longitude:
            type: text
            nullable: true
        homeLatitude:
            type: text
            nullable: true
        homeLongitude:
            type: text
            nullable: true
        forGroom:
            type: boolean
            nulable: false
            options:
                default: true
        commentObjectId:
            type: string
            nullable: true
        deletedAt:
            type: date
            nullable: true
    manyToOne:
        template:
            targetEntity: Viettut\Entity\Core\Template
            inversedBy: cards
        author:
            targetEntity: Viettut\Bundle\UserBundle\Entity\User
    oneToMany:
        comments:
            targetEntity: Viettut\Entity\Core\Comment
            mappedBy: card


    lifecycleCallbacks: {  }
