Viettut\Entity\Core\Card:
    type: entity
    table: viettut_card
    repositoryClass: Viettut\Repository\Core\CardRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        hash:
            type: string
            length: 256
            nullable: false
        data:
            type: json_array
            nullable: false
        partyDate:
            type: datetime
            nullable: true
        weddingDate:
            type: datetime
            nullable: false
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        latitude:
            type: decimal
            scale: 7
            precision: 10
            nullable: true
        longitude:
            type: decimal
            scale: 7
            precision: 10
            nullable: true
        homeLatitude:
            type: decimal
            scale: 7
            precision: 10
            nullable: true
        homeLongitude:
            type: decimal
            scale: 7
            precision: 10
            nullable: true
        forGroom:
            type: boolean
            nulable: false
            options:
                default: true
        views:
            type: integer
            nullable: false
            options:
                default: 0
        name:
            type: string
            nullable: false
            length: 256
        deletedAt:
            type: date
            nullable: true
    manyToOne:
        template:
            targetEntity: Viettut\Entity\Core\Template
            inversedBy: cards
        libraryCard:
            targetEntity: Viettut\Entity\Core\LibraryCard
            inversedBy: cards
            cascade: ['persist']
        author:
            targetEntity: Viettut\Bundle\UserBundle\Entity\User
    oneToMany:
        comments:
            targetEntity: Viettut\Entity\Core\Comment
            cascade: ['persist', 'detach', 'remove']
            mappedBy: card
        statuses:
            targetEntity: Viettut\Entity\Core\Status
            mappedBy: card


    lifecycleCallbacks: {  }
