Viettut\Entity\Core\Comment:
    type: entity
    table: viettut_comment
    repositoryClass: Viettut\Repository\Core\CommentRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: string
            length: 256
            nullable: false
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: date
            nullable: true
    manyToOne:
        author:
            targetEntity: Viettut\Bundle\UserBundle\Entity\User
        card:
            targetEntity: Viettut\Entity\Core\Card
            inversedBy: comments

    lifecycleCallbacks: {  }
