Viettut\Entity\Core\Template:
    type: entity
    table: viettut_template
    repositoryClass: Viettut\Repository\Core\TemplateRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
            length: 256
        hash:
            type: string
            nullable: false
            length: 256
        path:
            type: string
            nullable: false
            length: 256
        data:
            type: json_array
            nullable: false
        columns:
            type: json_array
            nullable: false
        gallery:
            type: json_array
            nullable: true
        thumbnail:
            type: string
            nulable: false
            length: 256
        weddingDate:
            type: datetime
            nullable: false
        latitude:
            type: decimal
            scale: 7
            precision: 10
            nullable: true
        longitude:
            type: decimal
            scale: 7
            precision: 10
            nullable: true
        homeLatitude:
            type: decimal
            scale: 7
            precision: 10
            nullable: true
        homeLongitude:
            type: decimal
            scale: 7
            precision: 10
            nullable: true
        forGroom:
            type: boolean
            nulable: false
            options:
                default: true
        type:
            type: smallint
            nullable: false
            options:
                default: 1
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        deletedAt:
            type: date
            nullable: true
    lifecycleCallbacks: {  }
