Viettut\Entity\Core\Testimonial:
    type: entity
    table: viettut_testimonial
    repositoryClass: Viettut\Repository\Core\TestimonialRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            nullable: false
            length: 256
        profession:
            type: string
            nullable: false
            length: 256
        image:
            type: string
            nullable: false
            length: 256
        content:
            type: text
            nullable: false

        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create

    lifecycleCallbacks: {  }
