# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    # event dispatched on user action such as add, remove, delete
    viettut.events.handler_event: 'viettut.events.handler_event'
    jms_serializer.cache_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

    # voter
    viettut.security.auth.voter.card.class: Viettut\Security\Authorization\Voter\CardVoter
    viettut.long_date_extension.class: Viettut\Behaviors\FullDateExtension
    viettut.long_time_extension.class: Viettut\Behaviors\FullTimeExtension
    viettut.full_day_extension.class: Viettut\Behaviors\DayExtension
services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    viettut.handler.handler_abstract:
        class: Viettut\Handler\HandlerAbstract
        abstract: true
        public: false
        calls:
            - [setEventDispatcher, ["@event_dispatcher"]]
            - [setEvent, ['%viettut.events.handler_event%']]

    viettut.handler.authentication_success_handler:
        class: Viettut\Bundle\UserBundle\Handler\AuthenticationSuccessHandler
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
        arguments:
            - '@router'
            - '@session'
            - '%cookie_domain%'
            - '%cookie_path%'
            - '%cookie_lifetime%'

    # jms serializer cache
    cache.apc.jms_serializer:
        class: Doctrine\Common\Cache\ApcCache
        calls:
            - [setNamespace, ["jms_serializer"]]

    jms_serializer.metadata_cache.apc:
        class: Metadata\Cache\DoctrineCacheAdapter
        arguments:
            - ""
            - '@cache.apc.jms_serializer'

    viettut.paragraph_extension:
        class: Viettut\Bundle\WebBundle\Twig\ParagraphExtension
        public: false
        tags:
            - { name: twig.extension }

    # voter
    viettut.security.auth.voter.card:
        class:  '%viettut.security.auth.voter.card.class%'
        public: false
        tags:
            - { name: security.voter }

    viettut.twig.long_date_extension:
        class: %viettut.long_date_extension.class%
        tags:
            - { name: twig.extension }

    viettut.twig.long_time_extension:
        class: %viettut.long_time_extension.class%
        tags:
            - { name: twig.extension }

    viettut.twig.full_day_extension:
        class: %viettut.full_day_extension.class%
        tags:
            - { name: twig.extension }