Viettut\Entity\Core\Comment:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [comment.detail, comment.summary]
        content:
            expose: true
            groups: [comment.detail, comment.summary]
        author:
            expose: true
            groups: [comment.detail, comment.summary]
        card:
            expose: true
            groups: [comment.detail, comment.summary]
        createdAt:
            expose: true
            groups: [comment.detail, comment.summary]
