Viettut\Entity\Core\Card:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [card.detail, card.summary]
        hash:
            expose: true
            groups: [card.detail, card.summary]
        data:
            expose: true
            groups: [card.detail, card.summary]
        weddingDate:
            expose: true
            groups: [card.detail, card.summary]
        author:
            expose: true
            groups: [card.detail, card.summary]
        gallery:
            expose: true
            groups: [card.detail, card.summary]
        createdAt:
            expose: true
            groups: [card.detail, card.summary]
        latitude:
            expose: true
            groups: [card.detail, card.summary]
        longitude:
            expose: true
            groups: [card.detail, card.summary]
        forGroom:
            expose: true
            groups: [card.detail, card.summary]