api_get_token:
    path:      /getToken
    defaults:  { _controller: ViettutApiBundle:Token:getToken }
    methods:  [POST]

api_check_token:
    path:      /checkToken
    defaults:  { _controller: ViettutApiBundle:Token:checkToken }
    methods:  [POST]

api_reset_password_send_email:
    path: /resetting/sendEmail
    defaults: { _controller: ViettutApiBundle:ResetPassword:sendEmail }
    methods: [POST]

api_reset_password_reset:
    path: /resetting/reset/{token}
    defaults: { _controller: ViettutApiBundle:ResetPassword:reset }
    methods: [POST]

api_subscribe:
    type: rest
    resource: Viettut\Bundle\ApiBundle\Controller\SubscribeController
    name_prefix:  api_1_

api_comment:
    type: rest
    resource: Viettut\Bundle\ApiBundle\Controller\CommentController
    name_prefix:  api_1_

api_card:
    type: rest
    resource: Viettut\Bundle\ApiBundle\Controller\CardController
    name_prefix:  api_1_

api_template:
    type: rest
    resource: Viettut\Bundle\ApiBundle\Controller\TemplateController
    name_prefix:  api_1_

api_testimonial:
    type: rest
    resource: Viettut\Bundle\ApiBundle\Controller\TestimonialController
    name_prefix:  api_1_

api_faq:
    type: rest
    resource: Viettut\Bundle\ApiBundle\Controller\FaqController
    name_prefix:  api_1_

api_post:
    type: rest
    resource: Viettut\Bundle\ApiBundle\Controller\PostController
    name_prefix:  api_1_

api_status:
    type: rest
    resource: Viettut\Bundle\ApiBundle\Controller\StatusController
    name_prefix:  api_1_

api_engage:
    type: rest
    resource: Viettut\Bundle\ApiBundle\Controller\EngageController
    name_prefix:  api_1_