imports:
    - { resource: services/comment.services.yml }
    - { resource: services/subscriber.services.yml }
    - { resource: services/card.services.yml }
    - { resource: services/template.services.yml }
    - { resource: services/faq.services.yml }
    - { resource: services/post.services.yml }
    - { resource: services/testimonial.services.yml }

services:

    # handlers
    viettut.handler.role_handler_abstract:
        class: Viettut\Handler\RoleHandlerAbstract
        abstract: true
        public: false
        parent : viettut.handler.handler_abstract
        arguments:
            - '@form.factory'

    viettut.services.facebook_service:
        class: Viettut\Services\FacebookService
        arguments:
            - '%facebook_app_id%'
            - '%facebook_app_secret%'
            - '%facebook_graph_default_version%'
            - '%domain%'
            - '%http_schema%'
            - '%facebook_object_id_url_template%'
            - '@viettut.domain_manager.card'