imports:
    - { resource: services/comment.services.yml }
    - { resource: services/subscriber.services.yml }
    - { resource: services/card.services.yml }
    - { resource: services/template.services.yml }
    - { resource: services/faq.services.yml }
    - { resource: services/post.services.yml }
    - { resource: services/testimonial.services.yml }
    - { resource: services/status.services.yml }

services:

    # handlers
    viettut.handler.role_handler_abstract:
        class: Viettut\Handler\RoleHandlerAbstract
        abstract: true
        public: false
        parent : viettut.handler.handler_abstract
        arguments:
            - '@form.factory'

    viettut.services.image_optimizer:
        class: Viettut\Services\ImageOptimizer
        arguments:
            - '%image_quality%'

    viettut.services.social_service:
        class: Viettut\Services\SocialService
        arguments:
            - '%facebook_app_id%'
            - '%facebook_app_secret%'
            - '%facebook_redirect_uri%'
            - '%zalo_redirect_uri%'
            - '%google_client_id%'
            - '%google_client_secret%'
            - '%google_client_app_name%'
            - '%google_redirect_uri%'
            - '%facebook_album_redirect_uri%'
            - '%facebook_graph_default_version%'

    viettut.services.username_service:
        class: Viettut\Services\UsernameService
        arguments:
            - '@viettut_user.domain_manager.lecturer'

    viettut.event_listener.update_video_id_listener:
        class: Viettut\Bundle\ApiBundle\EventListener\UpdateVideoIdListener
        arguments:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    viettut.event_listener.update_geo_location_listener:
        class: Viettut\Bundle\ApiBundle\EventListener\UpdateGeoLocationListener
        arguments:
            - '%google_map_api_key%'
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    viettut.event_listener.set_default_card_data_listener:
        class: Viettut\Bundle\ApiBundle\EventListener\SetDefaultCardDataListener
        arguments:
            - '%admin_id%'
            - '%wedding_comment%'
            - '%exhibition_comment%'
            - '%birthday_comment%'

        tags:
            - { name: doctrine.event_listener, event: prePersist }