imports:
    - { resource: services/comment.services.yml }
    - { resource: services/subscriber.services.yml }
    - { resource: services/card.services.yml }
    - { resource: services/template.services.yml }

services:

    # handlers
    viettut.handler.role_handler_abstract:
        class: Viettut\Handler\RoleHandlerAbstract
        abstract: true
        public: false
        parent : viettut.handler.handler_abstract
        arguments:
            - '@form.factory'